### PR TITLE
Feat add bussinessday datepicker to all pages

### PR DESCRIPTION
**Pull request by BransonGitomeh**

### CODE REVIEW

**Comment by testyourcodenow** [comment]
LGTM

**Comment by BransonGitomeh** [comment]
damn conflicts, could you re-approve? fixed

**Comment by testyourcodenow** [comment]
LGTM

**Comment by testyourcodenow** [comment]
LGTM

**Comment by testyourcodenow** [comment]
LGTM

**Review by testyourcodenow — APPROVED** [review]
LGTM

**Pull request merged**
